### ISSUE TITLE
Isn't it useless without the "AI" function?

### ISSUE THREAD

**Issue by ekordev** [RyanLefebvre/LogSmarter#1]
The project is useless without the AI

**Comment by RyanLefebvre** [comment]
That's absolutely not true. I suggest reading the README. We only used machine learning for the initial prediction. We have not released documentation on how the rest of the algorithm works, although we might because we wrote a research paper on it. We are still deciding on what to do with that material.  

However, all of the source code is there for you to read if you choose to do so. The algorithm will still work and adjust over time, and users will still receive feedback on their data. The user management system still works, nutrition log CRUD still works, the cross platform payment processing system is here, the website source code is here and there are a ton of user interface components and useful views in the project. Marking this as closed for now. This app will pretty much work the same as it did before.
